### ISSUE TITLE
error at the encryptFileAndZipWithMetadata -  "Invalid params: string is undefined"

### ISSUE THREAD

**Issue by aymenx17** [Envoy-VC/arweave-lit-example#1]
I get an error on this line: 

`const res = await LitJsSdk.encryptFileAndZipWithMetadata({
				unifiedAccessControlConditions: conditions,
				authSig,
				chain: 'ethereum',
				file,
				litNodeClient: client,
				readme,
			});`

**Error:**
{
  message: "Invalid params: string is undefined",
  errorCode: "InvalidParamType",
  errorKind: "Validation",
  status: undefined,
  details: undefined,
}

**Comment by envoy1084** [comment]
@aymenx17 are you adding a readme text while uploading the file?

Readme is required, most probably adding readme should solve your error.

**Comment by aymenx17** [comment]
Yes it was that. Readme can't be an empty string. Thanks!
